spring:
  datasource:
    url: jdbc:postgresql://db-auth:5432/users-auth
    username: admin
    password: admin1234@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
